In [1]:
import pandas as pd
import numpy as np

In [2]:
ds=pd.read_csv("data2.csv")
ds

Unnamed: 0  Country   Age   Salary  Purchased
0           0   France  44.0  72000.0          0
1           1    Spain  27.0  48000.0          1
2           2  Germany  30.0  54000.0          0
3           3    Spain  38.0  61000.0          0
4           4  Germany  40.0      NaN          1
5           5   France  35.0  58000.0          1
6           6    Spain   NaN  52000.0          0
7           7   France  48.0  79000.0          1
8           8  Germany  50.0  83000.0          0
9           9   France  37.0  67000.0          1

In [16]:
ds.info

<bound method DataFrame.info of    Unnamed: 0  Country        Age        Salary  Purchased
0           0   France  44.000000  72000.000000          0
1           1    Spain  27.000000  48000.000000          1
2           2  Germany  30.000000  54000.000000          0
3           3    Spain  38.000000  61000.000000          0
4           4  Germany  40.000000  63777.777778          1
5           5   France  35.000000  58000.000000          1
6           6    Spain  38.777778  52000.000000          0
7           7   France  48.000000  79000.000000          1
8           8  Germany  50.000000  83000.000000          0
9           9   France  37.000000  67000.000000          1>

In [18]:
ds.isnull().sum()

Unnamed: 0    0
Country       0
Age           0
Salary        0
Purchased     0
dtype: int64

In [4]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  10 non-null     int64  
 1   Country     10 non-null     object 
 2   Age         9 non-null      float64
 3   Salary      9 non-null      float64
 4   Purchased   10 non-null     int64  
dtypes: float64(2), int64(2), object(1)
memory usage: 528.0+ bytes


In [5]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(ds[['Age','Salary']])
ds[['Age','Salary']]=imputer.transform(ds[['Age','Salary']])
ds

Unnamed: 0  Country        Age        Salary  Purchased
0           0   France  44.000000  72000.000000          0
1           1    Spain  27.000000  48000.000000          1
2           2  Germany  30.000000  54000.000000          0
3           3    Spain  38.000000  61000.000000          0
4           4  Germany  40.000000  63777.777778          1
5           5   France  35.000000  58000.000000          1
6           6    Spain  38.777778  52000.000000          0
7           7   France  48.000000  79000.000000          1
8           8  Germany  50.000000  83000.000000          0
9           9   France  37.000000  67000.000000          1

In [6]:
ds

Unnamed: 0  Country        Age        Salary  Purchased
0           0   France  44.000000  72000.000000          0
1           1    Spain  27.000000  48000.000000          1
2           2  Germany  30.000000  54000.000000          0
3           3    Spain  38.000000  61000.000000          0
4           4  Germany  40.000000  63777.777778          1
5           5   France  35.000000  58000.000000          1
6           6    Spain  38.777778  52000.000000          0
7           7   France  48.000000  79000.000000          1
8           8  Germany  50.000000  83000.000000          0
9           9   France  37.000000  67000.000000          1

In [7]:
x=ds.iloc[:,1:4].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])
x


array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [9]:
from sklearn.preprocessing import OneHotEncoder
dummy=pd.get_dummies(ds['Country'])
dummy

France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0

In [10]:
from sklearn.preprocessing import OneHotEncoder
onehot=OneHotEncoder()
onehot.fit_transform(ds.Country.values.reshape(-1,1)).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [11]:
y=ds.iloc[:,4].values
y


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_test

array([[1, 30.0, 54000.0],
       [1, 50.0, 83000.0]], dtype=object)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_train

array([[ 0.13483997,  0.26306757,  0.12381479],
       [-0.94387981, -0.25350148,  0.46175632],
       [ 1.21355975, -1.97539832, -1.53093341],
       [ 1.21355975,  0.05261351, -1.11141978],
       [-0.94387981,  1.64058505,  1.7202972 ],
       [ 1.21355975, -0.0813118 , -0.16751412],
       [-0.94387981,  0.95182631,  0.98614835],
       [-0.94387981, -0.59788085, -0.48214934]])

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_test=sc.fit_transform(x_test)
x_test

array([[ 0., -1., -1.],
       [ 0.,  1.,  1.]])

In [15]:
x=ds1.iloc[:,0:3].values
x

NameError: name 'ds1' is not defined

In [ ]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
x[:,0]=le1.fit_transform(x[:,0])
x

In [ ]:
from sklearn.preprocessing  import OneHotEncoder
onehot=OneHotEncoder()
onehot.fit_transform(ds1.Country.values.reshape(-1,1)).toarray()


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train

In [ ]:
ds1=pd.read_csv("Data1.csv")
ds1

In [ ]:
y=ds1.iloc[:,-1].values
y

In [ ]:
y=ds1.iloc[:,3].values
y

In [ ]:
from sklearn.preprocessing import LabelEncoder
le2=LabelEncoder()
y=le1.fit_transform(y)
y

# from sklearn.preprocessing import LabelEncoder
le2=LabelEncoder()
y[:,0]=le2.fit_transform(y[:,0])
ds1

In [ ]:
ds1