In [1]:
import numpy as np
from numpy.linalg import eigh, norm

In [2]:
# Define your input matrix A (3x3)

In [3]:
A = np.array([[1, 0, 2],
              [0, 1, 3],
              [-1, 1, 4]])

In [4]:
A

array([[ 1,  0,  2],
       [ 0,  1,  3],
       [-1,  1,  4]])

In [5]:
# Step 1: Calculate A^T * A

In [6]:
ATA = A.T.dot(A)


In [7]:
ATA 

array([[ 2, -1, -2],
       [-1,  2,  7],
       [-2,  7, 29]])

In [10]:
# Step 2: Calculate the eigenvalues and eigenvectors of ATA using eigh


In [11]:
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)

In [12]:
eigenvalues_ATA, eigenvectors_ATA

(array([ 0.14714054,  1.98130664, 30.87155282]),
 array([[-0.28133295,  0.95665031, -0.07531243],
        [-0.93684388, -0.2568173 ,  0.23742036],
        [ 0.20778673,  0.13735015,  0.96848315]]))

In [14]:
# Step 3: Sort eigenvalues and eigenvectors in descending order


In [13]:
sorted_indices = np.argsort(eigenvalues_ATA)[::-1]
eigenvalues_ATA = eigenvalues_ATA[sorted_indices]
eigenvectors_ATA = eigenvectors_ATA[:, sorted_indices]

In [ ]:
# Step 4: Calculate singular values from the square root of eigenvalues


In [15]:
singular_values = np.sqrt(eigenvalues_ATA)

In [16]:
singular_values

array([5.55621749, 1.40758895, 0.38358902])

In [ ]:
# Step 5: Create the diagonal matrix S (3x3)


In [28]:
S = np.zeros_like(A, dtype=float)
S[:A.shape[0], :A.shape[1]] = np.diag(singular_values)

In [30]:
S[:A.shape[0], :A.shape[1]]

array([[5.55621749, 0.        , 0.        ],
       [0.        , 1.40758895, 0.        ],
       [0.        , 0.        , 0.38358902]])

In [19]:
# Step 6: Calculate U from A and the eigenvectors of ATA


In [20]:
U = A.dot(eigenvectors_ATA)

In [22]:
# Normalize U to make it an orthonormal matrix


In [23]:
U /= norm(U, axis=0)

In [24]:
# Step 7: Calculate Vt (transpose of V) from the eigenvectors of ATA


In [25]:
Vt = eigenvectors_ATA.T



In [26]:
# Print the matrices U, S, and Vt


In [27]:
print("Matrix U (3x3):")
print(U)
print("\nMatrix S (3x3):")
print(S)
print("\nMatrix Vt (3x3):")
print(Vt)

Matrix U (3x3):
[[ 0.33505778  0.87479418  0.34995918]
 [ 0.56564917  0.11028302 -0.81723844]
 [ 0.75350999 -0.47177622  0.45787542]]

Matrix S (3x3):
[[5.55621749 0.         0.        ]
 [0.         1.40758895 0.        ]
 [0.         0.         0.38358902]]

Matrix Vt (3x3):
[[-0.07531243  0.23742036  0.96848315]
 [ 0.95665031 -0.2568173   0.13735015]
 [-0.28133295 -0.93684388  0.20778673]]
