In [ ]:
import numpy as np
from numpy.linalg import eigh,norm

In [5]:
A = np.array([[-5,2,3],
              [2,5,1],
              [-3,1,-5]])
A

array([[-5,  2,  3],
       [ 2,  5,  1],
       [-3,  1, -5]])

In [8]:
# step -1 calculate the A^T * A
ATA = A.T.dot(A)
ATA

array([[38, -3,  2],
       [-3, 30,  6],
       [ 2,  6, 35]])

In [10]:
#step -2 calculate the eignvalues and eignvectors by using eigh
evalues_ATA, ev_ATA = eigh(ATA)

In [13]:
evalues_ATA,ev_ATA

(array([25., 39., 39.]),
 array([[ 0.26726124, -0.96362411,  0.        ],
        [ 0.80178373,  0.22237479,  0.5547002 ],
        [-0.53452248, -0.14824986,  0.83205029]]))

In [17]:
# step -3 sort the eignvalues and eignvectors in desecending order
sorted_indices = np.argsort(evalues_ATA)[::-1]
evalues_ATA = evalues_ATA[sorted_indices]
ev_ATA = ev_ATA[:, sorted_indices]

In [21]:
# Step 4: Calculate singular values from the square root of eigenvalues

singular_values = np.sqrt(evalues_ATA)
singular_values

array([6.244998, 6.244998, 5.      ])

In [24]:
# Step 5: Create the diagonal matrix S (3x3)

S = np.zeros_like(A, dtype=float)
S[:A.shape[0], :A.shape[1]] = np.diag(singular_values)
S[:A.shape[0], :A.shape[1]]

array([[6.244998, 0.      , 0.      ],
       [0.      , 6.244998, 0.      ],
       [0.      , 0.      , 5.      ]])

In [32]:
# Step 6: Calculate U from A and the eigenvectors of ATA

U = A.dot(ev_ATA)

In [29]:
# Normalize U to make it an orthonormal matrix

U /= norm(U, axis=0)

In [30]:
# Step 7: Calculate Vt (transpose of V) from the eigenvectors of ATA

Vt = ev_ATA.T

In [33]:
# Print the matrices U, S, and Vt

print("Matrix U (3x3):")
print(U)
print("\nMatrix S (3x3):")
print(S)
print("\nMatrix Vt (3x3):")
print(Vt)

Matrix U (3x3):
[[ 3.60555128  4.81812056 -1.33630621]
 [ 3.60555128 -0.96362411  4.00891863]
 [-3.60555128  3.85449645  2.67261242]]

Matrix S (3x3):
[[6.244998 0.       0.      ]
 [0.       6.244998 0.      ]
 [0.       0.       5.      ]]

Matrix Vt (3x3):
[[ 0.          0.5547002   0.83205029]
 [-0.96362411  0.22237479 -0.14824986]
 [ 0.26726124  0.80178373 -0.53452248]]
